# .github/workflows/deploy-lambda.yml
name: deploy-lambda

on:
  workflow_call:
    inputs:
      function-name:
        required: true
        type: string
      region:
        required: false
        default: us-east-1
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # needed for OIDC
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.GHA_AWS_ROLE_ARN }}
          aws-region: ${{ inputs.region }}

      - name: Install dependencies
        run: |
          # adjust for your language:
          npm ci || pip install -r requirements.txt

      - name: Zip and deploy
        run: |
          zip -r function.zip .
          aws lambda update-function-code \
            --function-name "${{ inputs.function-name }}" \
            --zip-file fileb://function.zip
