# .github/workflows/deploy-lambda.yml
name: deploy-lambda

on:
  workflow_call:
    inputs:
      function-name:
        required: true
        type: string
      region:
        required: false
        default: us-east-1
        type: string
    secrets:
      GHA_AWS_ROLE_ARN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.GHA_AWS_ROLE_ARN }}
          aws-region: ${{ inputs.region }}
